version: "3.8"
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=dynamodb,s3,ssm,sns,sqs